### ISSUE TITLE
使用默认的3000端口，报already in use

### ISSUE THREAD

**Issue by julystone** [jrenc2002/GenLineAnimation-Server#1]
大佬好，我是up主视频跟过来的~

先直接npm start   说3000端口被占用了
随后尝试改了一下app.js的port为3001，启动出来了，但是网页内容是个Cannot GET /
![image](https://github.com/user-attachments/assets/ccf40df6-255e-4535-9dd0-6e55a703b764)

**Comment by jrenc2002** [comment]
localhost:3001/signature?name=JohnDoe&amp;animate=true&amp;speed=1&amp;color=%230000ff
让我瞅瞅👋
我看了一下，这是正常的，你直接访问“localhost:3001/signature?name=JohnDoe&amp;animate=true&amp;speed=1&amp;color=%230000ff”就能获取你想要的链接了。
不要访问http://localhost:3001/，我没有写http://localhost:3001/的代码，所以它会Cannot GET /


归家望月（青岛）软件有限公司
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jrenc2002/GenLineAnimation-Server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月22日(星期天) 晚上11:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[jrenc2002/GenLineAnimation-Server] 使用默认的3000端口，报already in use (Issue #1)





 
大佬好，我是up主视频跟过来的~
 
先直接npm start   说3000端口被占用了
 随后尝试改了一下app.js的port为3001，启动出来了，但是网页内容是个Cannot GET /
 image.png (view on web)

**Comment by julystone** [comment]
`http://localhost:3001/signature?name=JulyStone&animate=true&speed=1&color=%230000ff   `

用这个成功了，感谢感谢，发现用您复制的转义符（&amp）会导致失败的

那大佬后续会考虑做个主页/吗？

**Comment by jrenc2002** [comment]
考虑了~等有空了用electron做个小应用🤗然后可以导出svg/gif/mp4
